/******************************************************************************/
/****              Generated by IBExpert 18/10/2019 12:58:57               ****/
/******************************************************************************/

/******************************************************************************/
/****     Following SET SQL DIALECT is just for the Database Comparer      ****/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/


CREATE GENERATOR GEN_CLIENTE_ID;

CREATE TABLE CLIENTE (
    ID            INTEGER NOT NULL,
    RAZAOSOCIAL   VARCHAR(100) NOT NULL,
    NOMEFANTASIA  VARCHAR(100) NOT NULL,
    CNPJ          VARCHAR(14) NOT NULL,
    ENDERECO      VARCHAR(100) NOT NULL,
    TELEFONE      VARCHAR(20),
    EMAIL         VARCHAR(50),
    CREATEDAT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATEDAT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (ID);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: CLIENTE_BI */
CREATE OR ALTER TRIGGER CLIENTE_BI FOR CLIENTE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_cliente_id,1);
end
^


SET TERM ; ^



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/
