/******************************************************************************/
/****              Generated by IBExpert 18/10/2019 12:59:51               ****/
/******************************************************************************/

/******************************************************************************/
/****     Following SET SQL DIALECT is just for the Database Comparer      ****/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/


CREATE GENERATOR GEN_PRODUTO_ID;

CREATE TABLE PRODUTO (
    ID          INTEGER NOT NULL,
    DESCRICAO   VARCHAR(100) NOT NULL,
    CUSTO       NUMERIC(15,5) NOT NULL,
    PRECOVENDA  NUMERIC(15,5) NOT NULL,
    CREATEDAT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATEDAT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE PRODUTO ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (ID);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: PRODUTO_BI */
CREATE OR ALTER TRIGGER PRODUTO_BI FOR PRODUTO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_produto_id,1);
end
^


SET TERM ; ^



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/
