/******************************************************************************/
/****              Generated by IBExpert 18/10/2019 13:00:27               ****/
/******************************************************************************/

/******************************************************************************/
/****     Following SET SQL DIALECT is just for the Database Comparer      ****/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/


CREATE GENERATOR GEN_PEDIDOVENDA_ID;

CREATE TABLE PEDIDOVENDA (
    ID          INTEGER NOT NULL,
    IDCLIENTE   INTEGER,
    VALORTOTAL  NUMERIC(15,2),
    CREATEDAT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE PEDIDOVENDA ADD CONSTRAINT PK_PEDIDOVENDA PRIMARY KEY (ID);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE PEDIDOVENDA ADD CONSTRAINT FK_PEDIDOVENDA_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (ID) ON UPDATE CASCADE;


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: PEDIDOVENDA_BI */
CREATE OR ALTER TRIGGER PEDIDOVENDA_BI FOR PEDIDOVENDA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_pedidovenda_id,1);
end
^


SET TERM ; ^



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/
